version: '3.8'

services:
  app:
    build: .
    container_name: dentcare_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dentcare_db:3306/db_dentalcare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=dentalcare
      - SPRING_DATASOURCE_PASSWORD=dentista
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dentcare_network
    volumes:
      # Persistir imágenes de estudios subidos en tu disco local
      - ./uploads_data:/app/src/main/resources/static/uploads

  db:
    image: mysql:8.0
    container_name: dentcare_db
    restart: always
    environment:
      - MYSQL_DATABASE=db_dentalcare
      - MYSQL_USER=dentalcare
      - MYSQL_PASSWORD=dentista
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dentcare_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dentcare_network:
    driver: bridge

volumes:
  db_data:
